/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_7 (
    input clk,
    input rst,
    input [7:0] led_state,
    output reg [3:0] led_cols,
    output reg [1:0] led_rows
  );
  
  
  
  localparam NUMBER_ROWS = 2'h2;
  
  localparam NUMBER_COLUMNS = 3'h4;
  
  reg [1:0] M_rows_d, M_rows_q = 1'h0;
  reg [3:0] M_cols_d, M_cols_q = 1'h0;
  
  always @* begin
    M_cols_d = M_cols_q;
    M_rows_d = M_rows_q;
    
    M_rows_d = 2'h1;
    led_cols = M_cols_q;
    led_rows = M_rows_q;
    if (M_rows_q == 2'h1) begin
      M_cols_d = led_state[0+3-:4];
      M_rows_d = M_rows_q << 1'h1;
    end else begin
      if (M_rows_q == 2'h2 || M_rows_q == 2'h0) begin
        M_cols_d = led_state[4+3-:4];
        M_rows_d = 2'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_rows_q <= 1'h0;
      M_cols_q <= 1'h0;
    end else begin
      M_rows_q <= M_rows_d;
      M_cols_q <= M_cols_d;
    end
  end
  
endmodule
